config/routes.rb
Rails.application.routes.draw do
  # get 'users/login', :to => 'users#login'

  devise_for :users,
             path: 'accounts',
             path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration' },
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/users/:id', to: 'users#show'
  resources :users, only: [:show], path: 'accounts'

  resources :posts, only: %i[index show new create edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  # has_many :photos, dependent: :destroy

  has_many_attached :images

  # def belongs_to?(user)
  #  Post.find_by(user_id: user.id, id: id)
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  validates :name, presence: true, length: { maximum: 50 }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      user.image = auth.info.image.gsub('_normal', '') # assuming the user model has an image
      user.uid = auth.uid
      user.provider = auth.provider
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :website, :bio])
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url
      end
    end

    def create
      auth = request.env["omniauth.auth"]
      user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Signed in!"
    end
  
    def failure
      redirect_to root_path
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to(:new_user_session) unless user_signed_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: %i[show destroy]

  def index
    @posts = Post.all.limit(10).includes(:user).order('created_at desc')
    @post = Post.new
  end

  def create
    @post = current_user.posts.create!(post_params)
    @post.images.attach(params[:post][:images])
    if @post.save
      redirect_to :posts
      flash[:notice] = 'Saved ---'
    else
      flash[:alert] = 'Something went wrong .....'
      redirect_to :posts
    end
  end

  def show; end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      flash[:alert] = "Sorry, you're not permitted to edit this post"
      redirect_to :root
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = 'Post successfully updated'
      redirect_to :post
    else
      flash[:alert] = 'Something went wrong'
      render('edit')
    end
    # @post = current_user.posts.update!(post_params)
    # if @post.save
    #   redirect_to :posts
    #   flash[:notice] = 'Saved ---'
    # else
    #   flash[:alert] = 'Something went wrong .....'
    #   redirect_to :posts
    # end
  end

  def destroy
    if @post.user == current_user
      if @post.destroy
        flash[:notice] = 'Post deleted'
      else
        flash[:alert] = 'Something went wrong'
      end
    else
      flash[:notice] = "You don't have permission to do that!"
    end
    redirect_to :root
  end

  private

  def find_post
    @post = Post.find_by id: params[:id]

    return if @post

    flash[:danger] = 'Post does not exist!'
    redirect_to :root
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    protected
  
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    return user.image if user.image?

    gravatar_id = Digest::MD5.hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= display_meta_tags site: 'Instagram • Capture, edit & share photos, videos & messages with friends & family.',
                          keywords: %w[udemy instagram clone],
                          description: "Create an account or log in to Instagram - A simple, fun & creative way to capture, edit & share photos, videos & messages with friends & family."%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <%= favicon_link_tag 'icon.png' %>
  </head>

  <body>
    <%= render 'shared/navbar' if current_user %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

    <% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          toastr.<%= type %>('<%= value %>')
        <% end %>
      </script>
    <% end %>
  </body>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-65590279-6"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-65590279-6');
  </script>
</html>

app/views/pages/home.html.erb
<%= link_to("Log out", :destroy_user_session, :method => :delete) %>

app/views/posts/_photos.html.erb
<%= link_to post_path(post) do %>
<% if post.images.size == 1 %>
<% if post.images.attached? %>
<% #post.images.each do |image| %>
<%= image_tag url_for(post.images.first.variant(resize_to_limit: [1080, 1080])), class: "card-img-top" %>
<% #end %>
<% end %>
<% else %>
<div id="carousel-post" class="carousel slide" data-ride="carousel"><%= post.id %>
    <div class="carousel-inner">
        <% post.images.each do |image| %>
        <% if image == post.images.first %>
        <div class="carousel-item active">
            <% else %>
            <div class="carousel-item">
                <% end %>
                <%= image_tag url_for(image.variant(resize_to_limit: [1080, 1080])), class: "card-img-top" %>
            </div>
            <% end %>
        </div>
        <a class="carousel-control-prev" href="#carousel-post-<%= post.id %>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel-post-<%= post.id %>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <% end %>
    <% end %>

app/views/posts/_posts_list.html.erb
<% @posts.each do |post| %>
<div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
        <%= link_to user_path(post.user), class: "no-text-decoration" do %>
        <%= image_tag avatar_url(post.user), class: "post-author-icon" %>
        <% end %>
        <%= link_to user_path(post.user), class: "normal-color no-text-decoration", title: post.user.name do %>
        <strong><%= post.user.name %></strong>
        <% end %>
        <% if @post.user == current_user %>
        <%= link_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
        <i class="far fa-trash-alt" aria-hidden="true"></i>
        <% end %>
        <% end %>
    </div>

    <% if post.images.size == 1 %>
    <% if post.images.attached? %>
    <%= image_tag url_for(post.images.first.variant(resize_to_limit: [1080, 1080])), class: "card-img-top" %>
    <% end %>
    <% else %>
    <div id="carousel-post" class="carousel slide" data-ride="carousel"><%= post.id %>
        <div class="carous el-inner">
            <% post.images.each do |image| %>
            <% if image == post.images.first %>
            <div class="carousel-item active">
                <% else %>
                <div class="carousel-item">
                    <% end %>
                    <%= image_tag url_for(image.variant(resize_to_limit: [1080, 1080])), class: "card-img-top" %>
                </div>
                <% end %>
            </div>
            <a class="carousel-control-prev" href="#carousel-post-<%= post.id %>" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-post-<%= post.id %>" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <% end %>

        <div class="card-body">
            <div class="row actions">
                <a href="#" class="core-sprite love hide-text">Love</a>
                <a href="#" class="core-sprite comment hide-text">Comment</a>
                <a href="#" class="core-sprite bookmark hide-text ml-auto">Bookmark</a>
            </div>
            <div><strong><%= pluralize(16, "like") %></strong></div>
            <div>
                <span><strong> <%= post.user.name %> </strong></span>
                <span><%= post.content %></span>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + " AGO", post_path(post), class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class=row actions>
                <form action="#" class="w-100">
                    <div>
                        <textarea class="form-control comment-input border-0" placeholder="Add a comment ....."
                            rows="1"></textarea>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <% end %>

app/views/posts/edit.html.erb
<div class="d-flex flex-column align-items-center mt-3">
    <div class="row post box col-xl-10 col-lg-11 col-xs-12">
        <div class="col-lg-8 col-md-7 px-0 d-flex post-show-img">
            <div class="align-self-center">
                <%= render "photos", {post: @post} %>
            </div>
        </div>
        <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">
            <div class="row px-3 d-flex align-items-center">
                <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
                <%= image_tag avatar_url(@post.user), class: "post-author-icon" %>
                <% end %>
                <%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center",
            title: @post.user.name do %>
                <strong><%= @post.user.name %></strong>
                <% end %>
                <% if @post.user == current_user %>
                <%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
                <i class="far fa-trash-alt" aria-hidden="true"></i>
                <% end %>
                <% end %>
            </div>
            <hr class="mb-0">
            <div class="comment-list py-2">
                <% if @post.content.present? %>
                <div>
                    <span>
                        <%= form_for(@post, :url => {:action => 'update'}, :html => {:multipart => true, :class => "p-0 border-0"}) do |f| %>
                        <div class="form-group row mt-2">
                            <div class="col pr-0">
                                <%= f.text_field :content, class: "form-control border-0", placeholder: "Say something about this ...." %>
                            </div>
                        </div>
                        <%= f.submit "Update post", class: "btn btn-primary" %>
                        <% end %>

                    </span>
                </div>
                <% end %>
                <!-- load comment -->
                <div id="comment-post-<%= @post.id.to_s %>">
                    <% #render 'comment_list', post: @post %>
                </div>
            </div>
            <hr class="mt-0">

            <div class="row actions">
                <div id="like-icon-post-<%= @post.id.to_s %>">
                    <% #render "like_icon", {is_liked: @is_liked, post: @post} %>
                </div>
                <a href="#" class="core-sprite comment hide-text">Comment</a>
                <div id="bookmark-icon-post-<%= @post.id.to_s %>" class="ml-auto">
                    <% #render "bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>
                </div>
            </div>
            <div id="like-text-post-<%= @post.id.to_s %>">
                <% #render "like_text", {likes: @likes} %>
            </div>
            <div class="light-color post-time"><%= time_ago_in_words(@post.created_at).upcase %> AGO</div>
            <hr>
            <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
                <% #render 'comment_form', post: @post %>
            </div>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class: "d-flex flex-column align-items-center mt-3">
    <div class: "col-xl-7 col-lg-8 col-md-10 col-sm-1 post-card">
        <div class="card">
            <div class="card-header">
                Create post
            </div>
            <div class="card-body">
                <%= form_for(@post, :html => {:multipart => true, :class => "dropzone upload-image p-0 border-0"}) do |f| %>
                <div class="form-group row mt-2">
                    <div class="col-auto pr-0">
                        <%= image_tag avatar_url(current_user), class: "post-author-icon" %>
                    </div>
                    <div class="col pr-0">
                        <%= f.text_field :content, class: "form-control border-0", placeholder: "Say something about this ...." %>
                    </div>
                </div>
                <div class="fallback">
                    <%= f.file_field :images, multiple: true %>
                </div>
                <div class="dz-message m-0"></div>
                <div class="dropzone-previews mb-3">
                    <div class="upload-photos-icon">
                        <i class="fa fa-plus fa-2x" aria-hidden="true" style="color: #dddfe2;"></i>
                    </div>
                </div>
                <%= f.submit "Post", class: "btn btn-primary" %>
                <% end %>
            </div>
        </div>
        <div id="posts">
            <%= render 'posts_list' %>
        </div>
    </div>
    </br>
    <% #will_paginate @posts %>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
    <div class="row post box col-xl-10 col-lg-11 col-xs-12">
        <div class="col-lg-8 col-md-7 px-0 d-flex post-show-img">
            <div class="align-self-center">
                <%= render "photos", {post: @post} %>
            </div>
        </div>
        <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">
            <div class="row px-3 d-flex align-items-center">
                <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
                <%= image_tag avatar_url(@post.user), class: "post-author-icon" %>
                <% end %>
                <%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center",
            title: @post.user.name do %>
                <strong><%= @post.user.name %></strong>
                <% end %>
                <% if @post.is_belongs_to? current_user %>
                <%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
                <i class="far fa-trash-alt" aria-hidden="true"></i>
                <% end %>
                <% end %>
            </div>
            <hr class="mb-0">
            <div class="comment-list py-2">
                <% if @post.content.present? %>
                <div>
                    <span><strong><%= @post.user.name %></strong></span>
                    <span><%= @post.content %></span>
                </div>
                <% end %>
                <!-- load comment -->
                <div id="comment-post-<%= @post.id.to_s %>">
                    <%= render 'comment_list', post: @post %>
                </div>
            </div>
            <hr class="mt-0">

            <div class="row actions">
                <div id="like-icon-post-<%= @post.id.to_s %>">
                    <%= render "like_icon", {is_liked: @is_liked, post: @post} %>
                </div>
                <a href="#" class="core-sprite comment hide-text">Comment</a>
                <div id="bookmark-icon-post-<%= @post.id.to_s %>" class="ml-auto">
                    <%= render "bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>
                </div>
            </div>
            <div id="like-text-post-<%= @post.id.to_s %>">
                <%= render "like_text", {likes: @likes} %>
            </div>
            <div class="light-color post-time"><%= time_ago_in_words(@post.created_at).upcase %> AGO</div>
            <hr>
            <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
                <%= render 'comment_form', post: @post %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_devisemsg.html.erb
<% if resource.errors.any? %>
    <script type="text/javascript">
        <% resource.errors.full_messages.each do |value| %>
            toastr.error('<%= value %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav mx-auto">
                <a href="" class="nav-item nav-link" href="#">ABOUT US</a>
                <a href="" class="nav-item nav-link" href="#">SUPPORT</a>
                <a href="" class="nav-item nav-link" href="#">BLOG</a>
                <a href="" class="nav-item nav-link" href="#">PRESS</a>
                <a href="" class="nav-item nav-link" href="#">API</a>
                <a href="" class="nav-item nav-link" href="#">JOB</a>
                <a href="" class="nav-item nav-link" href="#">PRIVACY</a>
                <a href="" class="nav-item nav-link" href="#">TERMS</a>
                <a href="" class="nav-item nav-link" href="#">DIRECTORY</a>
                <a href="" class="nav-item nav-link" href="#">LANGUAGE</a>
            </div>
        </div>
    </nav>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class = "container">

  <%= link_to("Afrigram logo", :root, :class => "navbar-brand core-sprite hide-text") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <form class="form-inline my-2 my-lg-0 ml-md-auto">
      <input class="form-control mr-sm-2 text-center common-btn" type="search" placeholder="Search" aria-label="Search">
    </form>
    <ul class="navbar-nav ml-md-auto">
      <li class="nav-item">
        <a class="nav-link core-sprite explore-icon hide-text" href="#">Explore</a>
      </li>
      <li class="nav-item">
        <a class="nav-link core-sprite notification-icon hide-text" href="#">Notification</a>
      </li>
      <li class="nav-item">
        <%= link_to "Profile", user_path(current_user), class: "nav-link core-sprite profile-icon hide-text" %>
      </li>
    </ul>
  </div>
  </div>
  </nav>

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <%= image_tag avatar_url(@user), width: '152', height: '152', class: "round-img" %>
  </div>
  <div class="col-md-8">
    <div class="row">
      <p class="username"><%= @user.name %></p>
      <% if @user == current_user %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
        <button type="button" class="core-sprite setting" data-toggle="modal" data-target="#exampleModal"></button>
      <% end %>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="list-group text-center">
              <a href="#" class="list-group-item list-group-item-action">Change Password</a>
              <%= link_to "Log out", destroy_user_session_path, method: :delete,
                class: "list-group-item list-group-item-action" %>
              <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <p class="email"><%= @user.email %></p>
    </div>
  </div>

  <div class="profile-tab">
    <% if @user == current_user %>
    <nav>
      <div class="nav nav-tabs d-flex justify-content-center" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-posts-tab" data-toggle="tab" href="#nav-posts" role="tab" aria-controls="nav-posts" aria-selected="true">POSTS</a>
        <a class="nav-item nav-link" id="nav-saved-tab" data-toggle="tab" href="#nav-saved" role="tab" aria-controls="nav-saved" aria-selected="false">SAVED</a>
      </div>
    </nav>
    <% end %>
    <div class="tab-content pb-3" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-posts" role="tabpanel" aria-labelledby="nav-posts-tab">
        <div class="row">
          <%  %>
        </div>
      </div>
      <div class="tab-pane fade" id="nav-saved" role="tabpanel" aria-labelledby="nav-saved-tab">
        <div class="row">
        
        </div>
      </div>
    </div>
  </div>
</div>